import { getPublicGames } from "@/lib/db";
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Image, User, Calendar, Eye } from "lucide-react";
import StickerRenderer from "@/components/sticker-renderer";
import Link from "next/link";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";


export default async function PublicGamesPage() {
  const games = await getPublicGames(20);

  return (
    <div className="max-w-6xl mx-auto">
      <div className="mb-8">
        <h1 className="text-3xl font-bold mb-2">Public Stickers</h1>
        <p className="text-muted-foreground">
          Discover stickers created by the community. All stickers are generated by AI.
        </p>
      </div>

      {games.length === 0 ? (
        <Card>
          <CardContent className="py-12 text-center">
            <Image className="h-12 w-12 mx-auto text-muted-foreground mb-4" />
            <h3 className="text-lg font-semibold mb-2">No public stickers yet</h3>
            <p className="text-muted-foreground mb-4">Be the first to create a sticker!</p>
            <Button asChild>
              <Link href="/">Create a Sticker</Link>
            </Button>
          </CardContent>
        </Card>
      ) : (
        <div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-6">
          {games.map((game: any) => (
            <Card key={game.id} className="flex flex-col">
              <CardHeader>
                <CardTitle className="line-clamp-1">{game.title}</CardTitle>
                <CardDescription className="line-clamp-2">
                  {game.description || "AI-generated sticker"}
                </CardDescription>
              </CardHeader>
              <CardContent className="flex-grow space-y-4">
                <div className="rounded-lg bg-muted p-4">
                  <StickerRenderer
                    content={game.htmlContent}
                    contentType={
                      game.contentType === "lottie"
                        ? "lottie"
                        : game.contentType === "svg-animated"
                          ? "svg-animated"
                          : "svg"
                    }
                    title={game.title}
                    className="w-full h-auto"
                  />
                </div>
                <div className="space-y-2 text-sm">
                  <div className="flex items-center gap-2">
                    <User className="h-4 w-4 text-muted-foreground" />
                    <span>{game.user?.name || game.user?.email || "Anonymous"}</span>
                  </div>
                  <div className="flex items-center gap-2">
                    <Calendar className="h-4 w-4 text-muted-foreground" />
                    <span>{new Date(game.createdAt).toLocaleDateString()}</span>
                  </div>
                  <div className="flex items-center gap-2">
                    <Eye className="h-4 w-4 text-muted-foreground" />
                    <span>{game.isPublic ? "Public" : "Private"}</span>
                  </div>
                </div>
              </CardContent>
              <CardFooter>
                <Button className="w-full" asChild>
                  <Link href={`/game/${game.id}`}>View Sticker</Link>
                </Button>
              </CardFooter>
            </Card>
          ))}
        </div>
      )}
    </div>
  );
}