import { NextRequest, NextResponse } from "next/server";
import OpenAI from "openai";
import { createGame } from "@/lib/db";
import { getServerSession } from "next-auth";
import { authOptions } from "@/lib/auth-options";

export const runtime = "nodejs";


// 初始化OpenAI客户端，连接到OpenRouter
const openai = new OpenAI({
  baseURL: "https://openrouter.ai/api/v1",
  apiKey: process.env.OPENROUTER_API_KEY,
  defaultHeaders: {
    "HTTP-Referer": process.env.NEXTAUTH_URL || "http://localhost:3000",
    "X-Title": "AI Game Generator",
  },
});

export async function POST(request: NextRequest) {
  try {
    // 获取用户会话（要求认证）
    const session = await getServerSession(authOptions);
    console.log("=== GENERATE API SESSION DEBUG ===");
    console.log("Full session data:", JSON.stringify(session, null, 2));
    console.log("Session exists:", !!session);
    console.log("Session user:", session?.user);
    console.log("Session user email:", session?.user?.email);
    console.log("Session user id:", session?.user?.id);
    
    if (!session?.user?.email) {
      console.log("ERROR: No session or email found - returning 401");
      return NextResponse.json(
        { 
          error: "Authentication required",
          debug: {
            hasSession: !!session,
            hasUser: !!session?.user,
            hasEmail: !!session?.user?.email
          }
        },
        { status: 401 }
      );
    }
    console.log("SUCCESS: User authenticated:", session.user.email, "User ID:", session.user.id);

    const { prompt } = await request.json();
    if (!prompt || typeof prompt !== "string") {
      return NextResponse.json({ error: "Prompt is required" }, { status: 400 });
    }

    // 检查API密钥
    if (!process.env.OPENROUTER_API_KEY) {
      console.error("OpenRouter API key is missing");
      return NextResponse.json(
        { error: "Server configuration error" },
        { status: 500 }
      );
    }

    // 调用 OpenRouter OpenAI GPT-5.1-Codex-Mini
    console.log("Calling OpenAI GPT-5.1-Codex-Mini with prompt:", prompt.substring(0, 100));
    const completion = await openai.chat.completions.create({
      model: "openai/gpt-5.1-codex-mini",
      provider: { order: ["openai"] },
      messages: [
        {
          role: "system",
          content: `You are a game developer AI that creates simple, self-contained HTML5 games. Generate a complete HTML file with embedded CSS and JavaScript that implements the described game. The game should be playable directly in a browser, with no external dependencies. Include a canvas or DOM-based game with clear controls and instructions. Keep the code concise and well-commented. Respond with ONLY the HTML code, no explanations.`,
        },
        {
          role: "user",
          content: `Create a simple game: ${prompt}. The HTML file should include:
1. A canvas or DOM elements for the game
2. Embedded CSS for styling
3. Embedded JavaScript for game logic
4. Clear instructions on how to play
5. A score display if applicable
6. Responsive design that works on desktop and mobile`,
        },
      ],
      temperature: 0.7,
      max_tokens: 4096,
    } as any);

    let htmlContent = completion.choices[0].message.content;
    if (!htmlContent) {
      throw new Error("No content generated by AI");
    }

    // Strip markdown code fences if present
    htmlContent = htmlContent.trim();
    if (htmlContent.startsWith("```")) {
      htmlContent = htmlContent
        .replace(/^```[a-zA-Z]*\n?/, "")
        .replace(/```\s*$/, "")
        .trim();
    }

    console.log("Game generated successfully, length:", htmlContent.length);

    // 创建游戏记录到数据库
    const game = await createGame({
      title: prompt.substring(0, 50) + (prompt.length > 50 ? "..." : ""),
      description: `AI-generated game from prompt: ${prompt}`,
      prompt,
      htmlContent,
      isPublic: true,
      userId: session.user.email, // 使用邮箱确保存在用户记录
    });

    return NextResponse.json({
      success: true,
      gameId: game.id,
      title: game.title,
      htmlContent: game.htmlContent,
      message: "Game generated successfully!",
    });
  } catch (error: any) {
    console.error("Game generation error:", error);
    
    // 提供更详细的错误信息
    let errorMessage = "Failed to generate game";
    if (error.code === 403) {
      errorMessage = "The selected model is not available in your region or there is an issue with your OpenRouter account.";
    } else if (error.message?.includes("API key")) {
      errorMessage = "Invalid OpenRouter API key. Please check your configuration.";
    } else if (error.message?.includes("model")) {
      errorMessage = "Model configuration error. Please check if OpenAI GPT-5.1-Codex-Mini (openai/gpt-5.1-codex-mini) is available on OpenRouter.";
    }

    return NextResponse.json(
      { 
        error: errorMessage, 
        details: error.message || String(error),
        code: error.code
      },
      { status: 500 }
    );
  }
}