import { NextRequest, NextResponse } from "next/server";
import OpenAI from "openai";
import { createGame } from "@/lib/db";
import { getServerSession } from "next-auth";
import { authOptions } from "@/lib/auth-options";

export const runtime = "nodejs";


// 初始化OpenAI客户端，连接到OpenRouter
const openai = new OpenAI({
  baseURL: "https://openrouter.ai/api/v1",
  apiKey: process.env.OPENROUTER_API_KEY,
  defaultHeaders: {
    "HTTP-Referer": process.env.NEXTAUTH_URL || "http://localhost:3000",
    "X-Title": "AI Game Generator",
  },
});

export async function POST(request: NextRequest) {
  try {
    // 获取用户会话（要求认证）
    const session = await getServerSession(authOptions);
    console.log("=== GENERATE API SESSION DEBUG ===");
    console.log("Full session data:", JSON.stringify(session, null, 2));
    console.log("Session exists:", !!session);
    console.log("Session user:", session?.user);
    console.log("Session user email:", session?.user?.email);
    console.log("Session user id:", session?.user?.id);
    
    if (!session?.user?.email) {
      console.log("ERROR: No session or email found - returning 401");
      return NextResponse.json(
        { 
          error: "Authentication required",
          debug: {
            hasSession: !!session,
            hasUser: !!session?.user,
            hasEmail: !!session?.user?.email
          }
        },
        { status: 401 }
      );
    }
    console.log("SUCCESS: User authenticated:", session.user.email, "User ID:", session.user.id);

    const { prompt, isAnimated } = await request.json();
    const animated = Boolean(isAnimated);
    if (!prompt || typeof prompt !== "string") {
      return NextResponse.json({ error: "Prompt is required" }, { status: 400 });
    }

    // 检查API密钥
    if (!process.env.OPENROUTER_API_KEY) {
      console.error("OpenRouter API key is missing");
      return NextResponse.json(
        { error: "Server configuration error" },
        { status: 500 }
      );
    }



    const normalizeHtml = (content: string) => {
      let result = content.trim();
      if (result.startsWith("```")) {
        result = result
          .replace(/^```[a-zA-Z]*\n?/, "")
          .replace(/```\s*$/, "")
          .trim();
      }
      return result;
    };


    const ensureAnimatedSvg = (content: string) => {
      if (!animated) return content;
      const lower = content.toLowerCase();
      if (lower.includes("<animate") || lower.includes("<animatetransform")) {
        return content;
      }
      const inject = "<animateTransform attributeName=\"transform\" type=\"rotate\" from=\"0 512 512\" to=\"360 512 512\" dur=\"2s\" repeatCount=\"indefinite\" />";
      return content.replace(/<svg([^>]*)>/i, `<svg$1>${inject}`);
    };

    const isHtmlComplete = (content: string) => {
      const lower = content.toLowerCase();
      return lower.includes("</html>") || lower.includes("</body>") || lower.includes("</svg>");
    };

    console.log("Calling OpenAI GPT-5.1-Codex-Mini with prompt:", prompt.substring(0, 100));

    const animationHint = animated
      ? "Include SVG animation using <animate> and/or <animateTransform>."
      : "No animation.";

    const createCompletion = () =>
      openai.chat.completions.create({
        model: "google/gemini-3-flash-preview",
        provider: { order: ["openrouter"] },
        messages: [
          {
            role: "system",
            content: `You are a sticker illustrator. Create a cute, clean SVG sticker based on the user prompt. Style: chibi proportions, big expressive eyes, soft pastel palette, clean bold outline, subtle shading, friendly mood. Composition: centered subject with generous padding, transparent background. OUTPUT:\n- Return ONLY valid SVG markup (no HTML, no code fences).\n- Use width=\"1024\" height=\"1024\" viewBox=\"0 0 1024 1024\".\n- Use simple paths/shapes; no external assets or embedded images.\n- Avoid text unless explicitly requested.\n- ${animationHint}`,
          },
          {
            role: "user",
            content: `Create a cute sticker SVG for: ${prompt}. Requirements:\n1. Single subject, centered, sticker-ready composition\n2. Thick clean outline and soft shading for depth\n3. Friendly, kawaii look with big expressive eyes\n4. High readability at small size\n5. 1:1 square composition\n6. ${animationHint}`,
          },
        ],
        temperature: 0.7,
        max_tokens: 8192,
      } as any);

    const completion = await createCompletion();

    let htmlContent = completion.choices[0].message.content;
    if (!htmlContent) {
      throw new Error("No content generated by AI");
    }

    htmlContent = normalizeHtml(htmlContent);
    htmlContent = ensureAnimatedSvg(htmlContent);

    if (!isHtmlComplete(htmlContent)) {
      console.warn("Generated HTML incomplete, retrying once...");
      const retryCompletion = await createCompletion();
      let retryContent = retryCompletion.choices[0].message.content || "";
      retryContent = normalizeHtml(retryContent);
      retryContent = ensureAnimatedSvg(retryContent);
      if (isHtmlComplete(retryContent)) {
        htmlContent = retryContent;
      }
    }

    console.log("Game generated successfully, length:", htmlContent.length);

    // 创建游戏记录到数据库
    const game = await createGame({
      title: prompt.substring(0, 50) + (prompt.length > 50 ? "..." : ""),
      description: `AI-generated game from prompt: ${prompt}`,
      prompt,
      htmlContent,
      contentType: animated ? "svg-animated" : "svg",
      isPublic: true,
      userId: session.user.email, // 使用邮箱确保存在用户记录
    });

    return NextResponse.json({
      success: true,
      gameId: game.id,
      title: game.title,
      htmlContent: game.htmlContent,
      contentType: game.contentType,
      message: "Game generated successfully!",
    });
  } catch (error: any) {
    console.error("Game generation error:", error);

    // 提供更详细的错误信息
    let errorMessage = "Failed to generate game";
    if (error.code === 403) {
      errorMessage = "The selected model is not available in your region or there is an issue with your OpenRouter account.";
    } else if (error.message?.includes("API key")) {
      errorMessage = "Invalid OpenRouter API key. Please check your configuration.";
    } else if (error.message?.includes("model")) {
      errorMessage = "Model configuration error. Please check if OpenAI GPT-5.1-Codex-Mini (openai/gpt-5.1-codex-mini) is available on OpenRouter.";
    }


    return NextResponse.json(
      {
        error: errorMessage,
        details: error.message || String(error),
        code: error.code,
      },
      { status: 500 }
    );
  }
}